// Generated by scripts/build-trundle-sprites.py. Don't edit by hand.

// Sheet layout, in source pixels before the 2x upscale.
export const SHEET = { columns: 5, rows: 4, cellWidth: 206, cellHeight: 224 };

// Feet sit this far above the bottom of a cell.
export const FLOOR_INSET = 6;

// Sprite pixels per pixel of trundle-body.png, for sizing the face.
export const FACE_SCALE = 0.15675;

// Frames 0-13 are him standing up from rest; 14-18 are the walk loop.
export const REST_FRAME = 0;
export const STAND_END = 13;
export const WALK_START = 14;
export const WALK_END = 18;

// Where the middle of his face goes in each frame's cell: [x, y].
export const FACE: [number, number][] = [
  [102.2, 169.1],
  [102.3, 167.5],
  [102.5, 165.1],
  [102.1, 157.1],
  [102.0, 147.5],
  [101.8, 135.1],
  [102.0, 126.1],
  [102.0, 119.1],
  [102.1, 115.1],
  [102.1, 116.1],
  [102.1, 117.5],
  [101.8, 117.5],
  [101.6, 119.5],
  [101.5, 120.1],
  [102.0, 123.6],
  [102.0, 123.1],
  [102.1, 122.8],
  [102.1, 123.8],
  [102.2, 124.6],
];
