const ts = require(process.cwd() + '/node_modules/typescript');
const fs = require('fs');
const assert = require('node:assert/strict');
const compiled = ts.transpileModule(fs.readFileSync('src/state/routine.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText;
const mod = { exports: {} }; new Function('exports', 'module', compiled)(mod.exports, mod);
const { restState, napFits } = mod.exports;
const base = { bedtime: 1320, morning: 420, naps: [], napUntil: null };
const at = (h, m = 0) => new Date(2026, 8, 21, h, m);
assert.equal(restState(base, at(22)).kind, 'bedtime');
assert.equal(restState(base, at(6,59)).kind, 'bedtime');
assert.equal(restState(base, at(7)).kind, 'awake');
const nap = { id: 'a', start: 840, end: 870 };
assert.equal(napFits(nap, base), true);
const scheduled = { ...base, naps: [nap] };
assert.equal(restState(scheduled, at(14)).kind, 'nap');
assert.equal(restState(scheduled, at(14,30)).kind, 'awake');
assert.equal(napFits({ id: 'b', start: 850, end: 880 }, scheduled), false);
assert.equal(napFits({ id: 'b', start: 870, end: 900 }, scheduled), true);
assert.equal(napFits({ id: 'b', start: 1310, end: 1330 }, base), false);
assert.equal(napFits({ id: 'b', start: 840, end: 840 }, base), false);
assert.equal(napFits({ id: 'b', start: 1380, end: 30 }, { ...base, bedtime: 480, morning: 960 }), true);
const manual = { ...base, napUntil: at(15).getTime() };
assert.equal(restState(manual, at(14,59)).kind, 'nap');
assert.equal(restState(manual, at(15)).kind, 'awake');
assert.equal(restState({ ...base, napUntil: at(23).getTime() }, at(22)).kind, 'bedtime');
assert.equal(restState({ ...scheduled, napUntil: at(14, 45).getTime() }, at(14, 10)).end, 885);
assert.equal(restState({ ...scheduled, napUntil: at(14, 10).getTime() }, at(13, 50)).end, 870);
assert.equal(restState({ ...base, napUntil: at(23).getTime() }, at(21, 50)).end, 1320);
const seconds = at(14, 10); seconds.setSeconds(50);
assert.equal(restState({ ...base, napUntil: at(14, 40).getTime() }, seconds).end, 880);
console.log('18 schedule assertions passed');
